### ISSUE TITLE
render_email extracts keys from options

### ISSUE THREAD

**Issue by kemptravis** [localmed/outbox-rails#8]
in [line 107 in notifier.rb](https://github.com/localmed/outbox-rails/blob/663de6bf33a074e53ed968873da2be058bc7f995/lib/outbox/notifier.rb#L107) `options` keys are being _extracted_ and somehow the empty object makes its way back to the calling method [render_message](https://github.com/localmed/outbox-rails/blob/663de6bf33a074e53ed968873da2be058bc7f995/lib/outbox/notifier.rb#L68). When `options` is passed to `render_message_types`, the object is empty. In the case I discovered this I passed `template_name` and it was able to be used in `render_email` where the template not found error would be thrown but not making it to `render_message_types` where the sms message would be rendered and and there is no error thrown if the template is not found. Plan is to change the code to use `select` rather than `extract!` and possibly return an error, warning, or log to let it be know that no templates were found in `render_message_types` if no matching templates are found... There could be cases where it is valid to have an email and not sms so perhaps the error or warning is not necessary.

**Comment by petebrowne** [comment]
> There could be cases where it is valid to have an email and not sms so perhaps the error or warning is not necessary.

Yeah that's true, most of the time we just setup an email template.
